server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "order-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/orders_database
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db.changelog-master.yaml
    url: jdbc:postgresql://localhost:15432/orders_database
    user: postgres
    password: postgres

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

topic:
  send-order: send-order-event